Repository ehddbs4521/Empty_Account_Guardians, pull requests merged in 2025-04, with the labels that each got.

#2 [FEAT] db.json 기본 세팅
  .DS_Store
  db.json
Labels: feat

#10 [FEAT] 사용자 데이터 가져오는 Pinia 생성
  db.json
  src/stores/counter.js
  src/stores/transaction.js
Labels: feat

#16 [FEAT] 목록 테이블 페이지네이션 / 필터 모달창 #8
  index.html
  src/components/FilterModal.vue
  src/components/TransactionList.vue
Labels: feat

#20 Refactor/17
  db.json
  src/pages/Chart.vue
Labels: refactor

#21 [FEAT] 캘린더 라이브러리 등록 및 데이터 호출
  package-lock.json
  package.json
  src/pages/Calendar.vue
  src/router/index.js
Labels: feat

#26 [FEAT] 월별 소비 추이 그래프
  src/pages/Chart.vue
Labels: feat

#28 [FEAT] 목록 테이블 카테고리/결제수단 필터
  package-lock.json
  src/components/FilterModal.vue
  src/components/TransactionList.vue
Labels: feat

#30 [FEAT] 특정 날짜를 클릭하면 세부 데이터 공개
  src/pages/Calendar.vue
Labels: feat

#33 [FEAT] 목록테이블 아이템 삭제 및 카테고리 색상 적용 #29
  src/components/TransactionList.vue
  src/stores/transaction.js
Labels: feat

#35 [FIX] pinia용 파일 수정
  src/stores/transaction.js
Labels: fix

#36 feat(Header.vue) : 헤더 구현 #27
  src/components/Header.vue
  src/router/index.js
Labels: feat

#39 [FEAT] 목록테이블 아이템 수정하기
  index.html
  src/components/EditTransactionModal.vue
  src/components/TransactionList.vue
  src/stores/transaction.js
Labels: feat

#43 [FEAT] 필터 모달 창 닫기 추가 및 목록테이블 수정
  src/components/FilterModal.vue
  src/components/TransactionList.vue
Labels: feat

#49 [FEAT] 로그인 및 회원가입
  db.json
  public/mascot.png
  public/wallet-icon.png
  src/pages/Login.vue
  src/pages/RegisterModal.vue
  src/router/index.js
  src/stores/transaction.js
Labels: feat

#51 [FIX] 사용자 데이터 가져올 때 닉네임도 같이 이용
  src/pages/RegisterModal.vue
  src/stores/transaction.js
Labels: fix

#54 [FEAT] 메인페이지 css#47
  src/components/EditTransactionModal.vue
  src/components/FilterModal.vue
  src/components/TransactionInputBar.vue
  src/components/TransactionList.vue
Labels: feat

#61 [DESIGN] Header.vue css
  package-lock.json
  package.json
  public/logo.png
  src/components/Header.vue
  src/main.js
  src/pages/Login.vue
  src/stores/user.js
Labels: design

#62 [FEAT] 차트 페이지 ) 수입 그래프 추가하기
  db.json
  src/pages/Chart.vue
Labels: feat

#65 [DESIGN] 회원가입 모달 css
  src/pages/RegisterModal.vue
Labels: design

#67 [FIX] App.vue 최초 로그인 시 내역 불러오기 오류 해결
  src/App.vue
Labels: fix

#69 [FEAT] 입금 시 lottie 애니메이션
  db.json
  package-lock.json
  package.json
  src/assets/Animation - 1744181634184.json
  src/main.js
  src/pages/Home.vue
Labels: feat

#70 [REFACTOR] 캘린더 디자인 수정 및 데이터 보여줌 refactor
  src/App.vue
  src/components/TransactionList.vue
  src/pages/Calendar.vue
  src/stores/transaction.js
Labels: refactor

#72 달력 동적으로 달 움직이기
  src/pages/Calendar.vue
Labels: fix

#77 [FIX] 캘린더 디자인 수정 및 카테고리 별 색깔 가져오기
  src/pages/Calendar.vue
Labels: fix

#78 [FEAT] 출금시 lottie 애니메이션 추가
  src/assets/expense_animation.json
  src/assets/income_animation.json
  src/components/TransactionInputBar.vue
  src/pages/Home.vue
Labels: feat

#80 [FIX] db.json 수정
  db.json
Labels: fix

#82 [FEAT] 월별 이동 화살표 -> 차트 페이지 연동 및 차트페이지 초기 렌더링
  src/pages/Chart.vue
Labels: feat

#90 [FIX] 수입/지출에 따른 카테고리 보이기
  db.json
  src/components/AddCategoryModal.vue
  src/components/TransactionInputBar.vue
Labels: fix

#92 [FIX] 수입/지출 총합 월 별로 수정
  src/components/TransactionList.vue
Labels: fix

#94 [FIX] 차트페이지 카테고리 색상 적용
  db.json
  src/components/TransactionList.vue
  src/pages/Chart.vue
Labels: fix

#97 [FIX] 차트페이지 반응형 css 적용
  package-lock.json
  package.json
  src/App.vue
  src/components/LineChart.vue
  src/components/PieChart.vue
  src/pages/Calendar.vue
  src/pages/Chart.vue
Labels: fix
